name: gradient_to_you
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # https://medium.com/flutter-jp/intl-beb5b9e8ee73
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  # https://pub.dev/packages/gradient_app_bar
  gradient_app_bar: ^0.0.1

  # https://pub.dev/packages/google_fonts
  google_fonts: ^0.2.0

  # https://mobx.pub/getting-started
  mobx: ^0.4.0
  flutter_mobx: ^0.3.4

  # https://pub.dev/packages/image_picker
  image_picker: ^0.6.3+1

  # https://pub.dev/packages/image_cropper
  image_cropper: ^1.2.0

  # https://pub.dev/packages/ext_storage
  ext_storage: ^1.0.2

  # https://pub.dev/packages/permission_handler
  permission_handler: ^4.4.0

  # https://pub.dev/packages/fluttertoast
  fluttertoast: ^3.1.3

  # https://pub.dev/packages/flutter_staggered_animations
  flutter_staggered_animations: ^0.1.2

  # https://pub.dev/packages/esys_flutter_share
  esys_flutter_share: ^1.0.2

  # https://pub.dev/packages/progressive_image
  progressive_image: ^1.0.1

  # https://pub.dev/packages/animated_text_kit
  animated_text_kit: ^2.0.0

  # https://pub.dev/packages/flutter_inner_drawer
  # Widget reloads when toggled if version is raised to 0.5.6+1 .
  flutter_inner_drawer: 0.5.5

  # https://pub.dev/packages/package_info
  package_info: ^0.4.0+17

  # https://pub.dev/packages/bubble_bottom_bar
  bubble_bottom_bar: ^1.2.0

  # https://pub.dev/packages/flutter_colorpicker
  flutter_colorpicker: ^0.3.4

  # https://pub.dev/packages/angles
  angles: ^1.2.1

  # https://pub.dev/packages/tutorial_coach_mark
  tutorial_coach_mark: ^0.3.0

  # https://pub.dev/packages/shared_preferences
  shared_preferences: ^0.5.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # https://medium.com/flutter-jp/intl-beb5b9e8ee73
  intl_translation: any

  # https://medium.com/flutter-jp/analysis-b8dbb19d3978
  pedantic_mono: any

  # https://pub.dev/packages/flutter_launcher_icons
  flutter_launcher_icons: ^0.7.3

  # https://mobx.pub/getting-started
  build_runner: ^1.3.1
  mobx_codegen: ^0.3.11

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon/icon.png
    - assets/images/splash1.webp
    - assets/images/thumbnail1.webp
    - assets/images/splash2.webp
    - assets/images/thumbnail2.webp
    - assets/images/splash3.webp
    - assets/images/thumbnail3.webp

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "assets/icon/background.png"
  adaptive_icon_foreground: "assets/icon/foreground.png"